-- 코드를 입력하세요
SELECT a.PRODUCT_CODE, SUM(SALES_AMOUNT)*a.PRICE AS SALES
FROM PRODUCT a
LEFT JOIN OFFLINE_SALE b
ON a.PRODUCT_ID = b.PRODUCT_ID
GROUP BY a.PRODUCT_CODE
ORDER BY SALES desc, a.PRODUCT_CODE asc;