SELECT
    B.TITLE,
    B.BOARD_ID,
    A.REPLY_ID,
    A.WRITER_ID,
    A.CONTENTS,
    DATE_FORMAT(A.CREATED_DATE, '%Y-%m-%d') AS CREATED_DATE
FROM USED_GOODS_REPLY AS A
INNER JOIN USED_GOODS_BOARD AS B
    ON A.BOARD_ID = B.BOARD_ID
WHERE B.CREATED_DATE >= '2022-10-01'
  AND B.CREATED_DATE < '2022-11-01'
ORDER BY A.CREATED_DATE ASC, B.TITLE ASC;